#!/usr/bin/python

# this tool builds the binary depending what kind of module it is.
# it can be a proprietary module or a open source module.


# check the build_info.py file 
# File will soon be converted to build_info 

# lets collect the list of all the module_info files


"""
 Acl (2.3.1) - 348 KB:

    Home page: https://savannah.nongnu.org/projects/acl

    Download: https://download.savannah.gnu.org/releases/acl/acl-2.3.1.tar.xz

    MD5 sum: 95ce715fe09acca7c12d3306d0f076b2
Attr (2.5.1) - 456 KB:

    Home page: https://savannah.nongnu.org/projects/attr

    Download: https://download.savannah.gnu.org/releases/attr/attr-2.5.1.tar.gz

    MD5 sum: ac1c5a7a084f0f83b8cace34211f64d8
Autoconf (2.71) - 1,263 KB:

    Home page: https://www.gnu.org/software/autoconf/

    Download: https://ftp.gnu.org/gnu/autoconf/autoconf-2.71.tar.xz

    MD5 sum: 12cfa1687ffa2606337efe1a64416106
Automake (1.16.4) - 1,564 KB:

    Home page: https://www.gnu.org/software/automake/

    Download: https://ftp.gnu.org/gnu/automake/automake-1.16.4.tar.xz

    MD5 sum: 86e8e682bd74e6390a016c4d9c11267c

    SHA256 sum: 80facc09885a57e6d49d06972c0ae1089c5fa8f4d4c7cfe5baea58e5085f136d
Bash (5.1.8) - 10,287 KB:

    Home page: https://www.gnu.org/software/bash/

    Download: https://ftp.gnu.org/gnu/bash/bash-5.1.8.tar.gz

    MD5 sum: 23eee6195b47318b9fd878e590ccb38c
Bc (5.0.0) - 420 KB:

    Home page: https://git.yzena.com/gavin/bc

    Download: https://github.com/gavinhoward/bc/releases/download/5.0.0/bc-5.0.0.tar.xz

    MD5 sum: 8345bb81c576ddfc8c27e0842370603c
Binutils (2.37) - 22,390 KB:

    Home page: https://www.gnu.org/software/binutils/

    Download: https://ftp.gnu.org/gnu/binutils/binutils-2.37.tar.xz

    MD5 sum: e78d9ff2976b745a348f4c1f27c77cb1
Bison (3.7.6) - 2,566 KB:

    Home page: https://www.gnu.org/software/bison/

    Download: https://ftp.gnu.org/gnu/bison/bison-3.7.6.tar.xz

    MD5 sum: d61aa92e3562cb7292b004ce96173cf7
Bzip2 (1.0.8) - 792 KB:

    Download: https://www.sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz

    MD5 sum: 67e051268d0c475ea773822f7500d0e5
Check (0.15.2) - 760 KB:

    Home page: https://libcheck.github.io/check

    Download: https://github.com/libcheck/check/releases/download/0.15.2/check-0.15.2.tar.gz

    MD5 sum: 50fcafcecde5a380415b12e9c574e0b2
Coreutils (8.32) - 5,418 KB:

    Home page: https://www.gnu.org/software/coreutils/

    Download: https://ftp.gnu.org/gnu/coreutils/coreutils-8.32.tar.xz

    MD5 sum: 022042695b7d5bcf1a93559a9735e668
DejaGNU (1.6.3) - 608 KB:

    Home page: https://www.gnu.org/software/dejagnu/

    Download: https://ftp.gnu.org/gnu/dejagnu/dejagnu-1.6.3.tar.gz

    MD5 sum: 68c5208c58236eba447d7d6d1326b821
Diffutils (3.8) - 1,548 KB:

    Home page: https://www.gnu.org/software/diffutils/

    Download: https://ftp.gnu.org/gnu/diffutils/diffutils-3.8.tar.xz

    MD5 sum: 6a6b0fdc72acfe3f2829aab477876fbc
E2fsprogs (1.46.4) - 9,298 KB:

    Home page: http://e2fsprogs.sourceforge.net/

    Download: https://downloads.sourceforge.net/project/e2fsprogs/e2fsprogs/v1.46.4/e2fsprogs-1.46.4.tar.gz

    MD5 sum: 128f5b0f0746b28d1e3ca7e263c57094
Elfutils (0.185) - 8,973 KB:

    Home page: https://sourceware.org/elfutils/

    Download: https://sourceware.org/ftp/elfutils/0.185/elfutils-0.185.tar.bz2

    MD5 sum: 2b6e94c2eebc1f2194173e31bca9396e
Eudev (3.2.10) - 1,916 KB:

    Download: https://dev.gentoo.org/~blueness/eudev/eudev-3.2.10.tar.gz

    MD5 sum: 60b135a189523f333cea5f71a3345c8d
Expat (2.4.1) - 435 KB:

    Home page: https://libexpat.github.io/

    Download: https://prdownloads.sourceforge.net/expat/expat-2.4.1.tar.xz

    MD5 sum: a4fb91a9441bcaec576d4c4a56fa3aa6
Expect (5.45.4) - 618 KB:

    Home page: https://core.tcl.tk/expect/

    Download: https://prdownloads.sourceforge.net/expect/expect5.45.4.tar.gz

    MD5 sum: 00fce8de158422f5ccd2666512329bd2
File (5.40) - 981 KB:

    Home page: https://www.darwinsys.com/file/

    Download: https://astron.com/pub/file/file-5.40.tar.gz

    MD5 sum: 72540ea1cc8c6e1dee35d6100ec66589
Findutils (4.8.0) - 1,940 KB:

    Home page: https://www.gnu.org/software/findutils/

    Download: https://ftp.gnu.org/gnu/findutils/findutils-4.8.0.tar.xz

    MD5 sum: eeefe2e6380931a77dfa6d9350b43186
Flex (2.6.4) - 1,386 KB:

    Home page: https://github.com/westes/flex

    Download: https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz

    MD5 sum: 2882e3179748cc9f9c23ec593d6adc8d
Gawk (5.1.0) - 3,081 KB:

    Home page: https://www.gnu.org/software/gawk/

    Download: https://ftp.gnu.org/gnu/gawk/gawk-5.1.0.tar.xz

    MD5 sum: 8470c34eeecc41c1aa0c5d89e630df50
GCC (11.2.0) - 78,996 KB:

    Home page: https://gcc.gnu.org/

    Download: https://ftp.gnu.org/gnu/gcc/gcc-11.2.0/gcc-11.2.0.tar.xz

    MD5 sum: 31c86f2ced76acac66992eeedce2fce2

    SHA256 sum: d08edc536b54c372a1010ff6619dd274c0f1603aa49212ba20f7aa2cda36fa8b
GDBM (1.20) - 965 KB:

    Home page: https://www.gnu.org/software/gdbm/

    Download: https://ftp.gnu.org/gnu/gdbm/gdbm-1.20.tar.gz

    MD5 sum: 006c19b8b60828fd6916a16f3496bd3c
Gettext (0.21) - 9,487 KB:

    Home page: https://www.gnu.org/software/gettext/

    Download: https://ftp.gnu.org/gnu/gettext/gettext-0.21.tar.xz

    MD5 sum: 40996bbaf7d1356d3c22e33a8b255b31
Glibc (2.34) - 16,896 KB:

    Home page: https://www.gnu.org/software/libc/

    Download: https://ftp.gnu.org/gnu/glibc/glibc-2.34.tar.xz

    MD5 sum: 31998b53fb39cb946e96abc310af1c89
GMP (6.2.1) - 1,980 KB:

    Home page: https://www.gnu.org/software/gmp/

    Download: https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.xz

    MD5 sum: 0b82665c4a92fd2ade7440c13fcaa42b
Gperf (3.1) - 1,188 KB:

    Home page: https://www.gnu.org/software/gperf/

    Download: https://ftp.gnu.org/gnu/gperf/gperf-3.1.tar.gz

    MD5 sum: 9e251c0a618ad0824b51117d5d9db87e
Grep (3.7) - 1,603 KB:

    Home page: https://www.gnu.org/software/grep/

    Download: https://ftp.gnu.org/gnu/grep/grep-3.7.tar.xz

    MD5 sum: 7c9cca97fa18670a21e72638c3e1dabf
Groff (1.22.4) - 4,044 KB:

    Home page: https://www.gnu.org/software/groff/

    Download: https://ftp.gnu.org/gnu/groff/groff-1.22.4.tar.gz

    MD5 sum: 08fb04335e2f5e73f23ea4c3adbf0c5f
GRUB (2.06) - 6,428 KB:

    Home page: https://www.gnu.org/software/grub/

    Download: https://ftp.gnu.org/gnu/grub/grub-2.06.tar.xz

    MD5 sum: cf0fd928b1e5479c8108ee52cb114363
Gzip (1.10) - 757 KB:

    Home page: https://www.gnu.org/software/gzip/

    Download: https://ftp.gnu.org/gnu/gzip/gzip-1.10.tar.xz

    MD5 sum: 691b1221694c3394f1c537df4eee39d3
Iana-Etc (20210611) - 579 KB:

    Home page: https://www.iana.org/protocols

    Download: https://github.com/Mic92/iana-etc/releases/download/20210611/iana-etc-20210611.tar.gz

    MD5 sum: f2854be57fe281e3ffc7364984467d2f
Inetutils (2.1) - 1,496 KB:

    Home page: https://www.gnu.org/software/inetutils/

    Download: https://ftp.gnu.org/gnu/inetutils/inetutils-2.1.tar.xz

    MD5 sum: 4e7676d1980e57c7df665e5c5c3c1047

    SHA256 sum: 01b9a4bc73a47e63f6e8a07b76122d9ad2a2e46ebf14870e9c91d660b5647a22
Intltool (0.51.0) - 159 KB:

    Home page: https://freedesktop.org/wiki/Software/intltool

    Download: https://launchpad.net/intltool/trunk/0.51.0/+download/intltool-0.51.0.tar.gz

    MD5 sum: 12e517cac2b57a0121cda351570f1e63
IPRoute2 (5.13.0) - 828 KB:

    Home page: https://www.kernel.org/pub/linux/utils/net/iproute2/

    Download: https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-5.13.0.tar.xz

    MD5 sum: 15fc3786303a173a14e180afe4cd2ecd
Kbd (2.4.0) - 1,095 KB:

    Home page: https://kbd-project.org/

    Download: https://www.kernel.org/pub/linux/utils/kbd/kbd-2.4.0.tar.xz

    MD5 sum: 3cac5be0096fcf7b32dcbd3c53831380
Kmod (29) - 548 KB:

    Download: https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-29.tar.xz

    MD5 sum: e81e63acd80697d001c8d85c1acb38a0
Less (590) - 348 KB:

    Home page: https://www.greenwoodsoftware.com/less/

    Download: https://www.greenwoodsoftware.com/less/less-590.tar.gz

    MD5 sum: f029087448357812fba450091a1172ab
LFS-Bootscripts (20210608) - 33 KB:

    Download: https://www.linuxfromscratch.org/lfs/downloads/11.0-rc3/lfs-bootscripts-20210608.tar.xz

    MD5 sum: 6efd60044ad31a603a2c31c68919a988
Libcap (2.53) - 153 KB:

    Home page: https://sites.google.com/site/fullycapable/

    Download: https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.53.tar.xz

    MD5 sum: 094994d4554c6689cf98ae4f717b8e19
Libffi (3.4.2) - 1,320 KB:

    Home page: https://sourceware.org/libffi/

    Download: https://github.com/libffi/libffi/releases/download/v3.4.2/libffi-3.4.2.tar.gz

    MD5 sum: 294b921e6cf9ab0fbaea4b639f8fdbe8
Libpipeline (1.5.3) - 972 KB:

    Home page: http://libpipeline.nongnu.org/

    Download: https://download.savannah.gnu.org/releases/libpipeline/libpipeline-1.5.3.tar.gz

    MD5 sum: dad443d0911cf9f0f1bd90a334bc9004
Libtool (2.4.6) - 951 KB:

    Home page: https://www.gnu.org/software/libtool/

    Download: https://ftp.gnu.org/gnu/libtool/libtool-2.4.6.tar.xz

    MD5 sum: 1bfb9b923f2c1339b4d2ce1807064aa5
Linux (5.13.12) - 116,545 KB:

    Home page: https://www.kernel.org/

    Download: https://www.kernel.org/pub/linux/kernel/v5.x/linux-5.13.12.tar.xz

    MD5 sum: 6e1728b2021ca19cc9273f080e6c44c7
    [Note] Note

    The Linux kernel is updated relatively often, many times due to discoveries of security vulnerabilities. The latest available stable kernel version may be used, unless the errata page says otherwise.

    For users with limited speed or expensive bandwidth who wish to update the Linux kernel, a baseline version of the package and patches can be downloaded separately. This may save some time or cost for a subsequent patch level upgrade within a minor release.
M4 (1.4.19) - 1,617 KB:

    Home page: https://www.gnu.org/software/m4/

    Download: https://ftp.gnu.org/gnu/m4/m4-1.4.19.tar.xz

    MD5 sum: 0d90823e1426f1da2fd872df0311298d
Make (4.3) - 2,263 KB:

    Home page: https://www.gnu.org/software/make/

    Download: https://ftp.gnu.org/gnu/make/make-4.3.tar.gz

    MD5 sum: fc7a67ea86ace13195b0bce683fd4469
Man-DB (2.9.4) - 1,865 KB:

    Home page: https://www.nongnu.org/man-db/

    Download: https://download.savannah.gnu.org/releases/man-db/man-db-2.9.4.tar.xz

    MD5 sum: 6e233a555f7b9ae91ce7cd0faa322bce
Man-pages (5.12) - 1,737 KB:

    Home page: https://www.kernel.org/doc/man-pages/

    Download: https://www.kernel.org/pub/linux/docs/man-pages/man-pages-5.12.tar.xz

    MD5 sum: 192132118f07369c88df267a92f3ef16
Meson (0.59.1) - 1,900 KB:

    Home page: https://mesonbuild.com

    Download: https://github.com/mesonbuild/meson/releases/download/0.59.1/meson-0.59.1.tar.gz

    MD5 sum: 9c8135ecde820094be2f42f457fb6535
MPC (1.2.1) - 820 KB:

    Home page: http://www.multiprecision.org/

    Download: https://ftp.gnu.org/gnu/mpc/mpc-1.2.1.tar.gz

    MD5 sum: 9f16c976c25bb0f76b50be749cd7a3a8
MPFR (4.1.0) - 1,490 KB:

    Home page: https://www.mpfr.org/

    Download: https://www.mpfr.org/mpfr-4.1.0/mpfr-4.1.0.tar.xz

    MD5 sum: bdd3d5efba9c17da8d83a35ec552baef
Ncurses (6.2) - 3,346 KB:

    Home page: https://www.gnu.org/software/ncurses/

    Download: https://ftp.gnu.org/gnu/ncurses/ncurses-6.2.tar.gz

    MD5 sum: e812da327b1c2214ac1aed440ea3ae8d
Ninja (1.10.2) - 209 KB:

    Home page: https://ninja-build.org/

    Download: https://github.com/ninja-build/ninja/archive/v1.10.2/ninja-1.10.2.tar.gz

    MD5 sum: 639f75bc2e3b19ab893eaf2c810d4eb4
OpenSSL (1.1.1l) - 9,604 KB:

    Home page: https://www.openssl.org/

    Download: https://www.openssl.org/source/openssl-1.1.1l.tar.gz

    MD5 sum: ac0d4387f3ba0ad741b0580dd45f6ff3
Patch (2.7.6) - 766 KB:

    Home page: https://savannah.gnu.org/projects/patch/

    Download: https://ftp.gnu.org/gnu/patch/patch-2.7.6.tar.xz

    MD5 sum: 78ad9937e4caadcba1526ef1853730d5
Perl (5.34.0) - 12,580 KB:

    Home page: https://www.perl.org/

    Download: https://www.cpan.org/src/5.0/perl-5.34.0.tar.xz

    MD5 sum: df7ecb0653440b26dc951ad9dbfab517
Pkg-config (0.29.2) - 1,970 KB:

    Home page: https://www.freedesktop.org/wiki/Software/pkg-config

    Download: https://pkg-config.freedesktop.org/releases/pkg-config-0.29.2.tar.gz

    MD5 sum: f6e931e319531b736fadc017f470e68a
Procps (3.3.17) - 985 KB:

    Home page: https://sourceforge.net/projects/procps-ng

    Download: https://sourceforge.net/projects/procps-ng/files/Production/procps-ng-3.3.17.tar.xz

    MD5 sum: d60613e88c2f442ebd462b5a75313d56
Psmisc (23.4) - 362 KB:

    Home page: https://gitlab.com/psmisc/psmisc

    Download: https://sourceforge.net/projects/psmisc/files/psmisc/psmisc-23.4.tar.xz

    MD5 sum: 8114cd4489b95308efe2509c3a406bbf
Python (3.9.6) - 18,608 KB:

    Home page: https://www.python.org/

    Download: https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tar.xz

    MD5 sum: ecc29a7688f86e550d29dba2ee66cf80
Python Documentation (3.9.6) - 6,692 KB:

    Download: https://www.python.org/ftp/python/doc/3.9.6/python-3.9.6-docs-html.tar.bz2

    MD5 sum: 0dae29e4c38af1b6b1a86b35c9e48923
Readline (8.1) - 2,924 KB:

    Home page: https://tiswww.case.edu/php/chet/readline/rltop.html

    Download: https://ftp.gnu.org/gnu/readline/readline-8.1.tar.gz

    MD5 sum: e9557dd5b1409f5d7b37ef717c64518e
Sed (4.8) - 1,317 KB:

    Home page: https://www.gnu.org/software/sed/

    Download: https://ftp.gnu.org/gnu/sed/sed-4.8.tar.xz

    MD5 sum: 6d906edfdb3202304059233f51f9a71d
Shadow (4.9) - 1,592 KB:

    Home page: https://shadow-maint.github.io/shadow/

    Download: https://github.com/shadow-maint/shadow/releases/download/v4.9/shadow-4.9.tar.xz

    MD5 sum: 126924090caf72f3de7e9261fd4e10ac
Sysklogd (1.5.1) - 88 KB:

    Home page: https://www.infodrom.org/projects/sysklogd/

    Download: https://www.infodrom.org/projects/sysklogd/download/sysklogd-1.5.1.tar.gz

    MD5 sum: c70599ab0d037fde724f7210c2c8d7f8
Sysvinit (2.99) - 124 KB:

    Home page: https://savannah.nongnu.org/projects/sysvinit

    Download: https://download.savannah.gnu.org/releases/sysvinit/sysvinit-2.99.tar.xz

    MD5 sum: 6abc0ea61b8dd4a41b4e931a43b1bb90
Tar (1.34) - 2,174 KB:

    Home page: https://www.gnu.org/software/tar/

    Download: https://ftp.gnu.org/gnu/tar/tar-1.34.tar.xz

    MD5 sum: 9a08d29a9ac4727130b5708347c0f5cf
Tcl (8.6.11) - 10,020 KB:

    Home page: http://tcl.sourceforge.net/

    Download: https://downloads.sourceforge.net/tcl/tcl8.6.11-src.tar.gz

    MD5 sum: 8a4c004f48984a03a7747e9ba06e4da4
Tcl Documentation (8.6.11) - 1,172 KB:

    Download: https://downloads.sourceforge.net/tcl/tcl8.6.11-html.tar.gz

    MD5 sum: e358a9140c3a171e42f18c8a7f6a36ea
Texinfo (6.8) - 4,848 KB:

    Home page: https://www.gnu.org/software/texinfo/

    Download: https://ftp.gnu.org/gnu/texinfo/texinfo-6.8.tar.xz

    MD5 sum: a91b404e30561a5df803e6eb3a53be71
Time Zone Data (2021a) - 403 KB:

    Home page: https://www.iana.org/time-zones

    Download: https://www.iana.org/time-zones/repository/releases/tzdata2021a.tar.gz

    MD5 sum: 20eae7d1da671c6eac56339c8df85bbd
Udev-lfs Tarball (udev-lfs-20171102) - 11 KB:

    Download: https://anduin.linuxfromscratch.org/LFS/udev-lfs-20171102.tar.xz

    MD5 sum: 27cd82f9a61422e186b9d6759ddf1634
Util-linux (2.37.2) - 5,490 KB:

    Home page: https://git.kernel.org/pub/scm/utils/util-linux/util-linux.git/

    Download: https://www.kernel.org/pub/linux/utils/util-linux/v2.37/util-linux-2.37.2.tar.xz

    MD5 sum: d659bf7cd417d93dc609872f6334b019
Vim (8.2.3337) - 15,311 KB:

    Home page: https://www.vim.org

    Download: https://anduin.linuxfromscratch.org/LFS/vim-8.2.3337.tar.gz

    MD5 sum: e0325a4988b1b99b9c2e46fa853c1980
    [Note] Note

    The version of vim changes daily. To get the latest version, go to https://github.com/vim/vim/releases.
XML::Parser (2.46) - 249 KB:

    Home page: https://github.com/chorny/XML-Parser

    Download: https://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-2.46.tar.gz

    MD5 sum: 80bb18a8e6240fcf7ec2f7b57601c170
Xz Utils (5.2.5) - 1,122 KB:

    Home page: https://tukaani.org/xz

    Download: https://tukaani.org/xz/xz-5.2.5.tar.xz

    MD5 sum: aa1621ec7013a19abab52a8aff04fe5b
Zlib (1.2.11) - 457 KB:

    Home page: https://www.zlib.net/

    Download: https://zlib.net/zlib-1.2.11.tar.xz

    MD5 sum: 85adef240c5f370b308da8c938951a68
Zstd (1.5.0) - 1,808 KB:

    Home page: https://facebook.github.io/zstd/

    Download: https://github.com/facebook/zstd/releases/download/v1.5.0/zstd-1.5.0.tar.gz 
"""


for line in open("out/.module_paths/module_info.list", "r").readlines():
    module_list = line.strip() 
    print (module_list)